import { Movie, Mood } from './types';

export const MOODS: { id: Mood; label: string; icon: string; color: string }[] = [
  { id: 'happy', label: 'Happy', icon: '😊', color: 'from-yellow-400 to-orange-500' },
  { id: 'sad', label: 'Sad', icon: '😢', color: 'from-blue-400 to-indigo-600' },
  { id: 'romantic', label: 'Romantic', icon: '❤️', color: 'from-pink-400 to-rose-600' },
  { id: 'thriller', label: 'Thriller', icon: '😱', color: 'from-purple-600 to-black' },
  { id: 'chill', label: 'Chill', icon: '🛋️', color: 'from-emerald-400 to-teal-600' },
];

export const MOVIES: Movie[] = [
  {
    id: '1',
    title: 'Interstellar',
    rating: 8.7,
    language: 'English',
    genre: ['Sci-Fi', 'Drama'],
    mood: ['chill', 'sad'],
    duration: '2h 49m',
    description: 'When Earth becomes uninhabitable, a team of ex-pilots and scientists travel through a wormhole in search of a new home for humanity.',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    banner: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1200&q=80',
    showtimes: ['10:30 AM', '02:00 PM', '06:30 PM', '09:45 PM'],
  },
  {
    id: '2',
    title: 'The Dark Knight',
    rating: 9.0,
    language: 'English',
    genre: ['Action', 'Thriller'],
    mood: ['thriller'],
    duration: '2h 32m',
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    poster: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=800&q=80',
    banner: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=1200&q=80',
    showtimes: ['11:00 AM', '03:15 PM', '07:00 PM', '10:30 PM'],
  },
  {
    id: '3',
    title: 'La La Land',
    rating: 8.0,
    language: 'English',
    genre: ['Musical', 'Romance'],
    mood: ['romantic', 'happy'],
    duration: '2h 8m',
    description: 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.',
    cast: ['Ryan Gosling', 'Emma Stone', 'John Legend'],
    poster: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=800&q=80',
    banner: 'https://images.unsplash.com/photo-1492691523567-30730009df34?auto=format&fit=crop&w=1200&q=80',
    showtimes: ['12:30 PM', '04:00 PM', '08:15 PM'],
  },
  {
    id: '4',
    title: 'Parasite',
    rating: 8.5,
    language: 'Korean',
    genre: ['Thriller', 'Drama'],
    mood: ['thriller', 'sad'],
    duration: '2h 12m',
    description: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'],
    poster: 'https://images.unsplash.com/photo-1594908900066-3f47337549d8?auto=format&fit=crop&w=800&q=80',
    banner: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1200&q=80',
    showtimes: ['01:30 PM', '05:45 PM', '09:00 PM'],
  },
  {
    id: '5',
    title: 'Soul',
    rating: 8.1,
    language: 'English',
    genre: ['Animation', 'Comedy'],
    mood: ['happy', 'chill'],
    duration: '1h 40m',
    description: 'After a musician who has lost his passion for music is transported out of his body, he must find his way back with the help of an infant soul learning about herself.',
    cast: ['Jamie Foxx', 'Tina Fey', 'Graham Norton'],
    poster: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=800&q=80',
    banner: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80',
    showtimes: ['10:00 AM', '12:45 PM', '03:30 PM', '06:15 PM'],
  }
];
